const { Books } = require('../models');



const bookdata = [
  {
    "title": "Gilead",
    "subtitle": "",
    "authors": "Marilynne Robinson",
    "categories": "Fiction",
    "thumbnail": "http://books.google.com/books/content?id=KQZCPgAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "description": "A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives. John Ames is a preacher, the son of a preacher and the grandson (both maternal and paternal) of preachers. It‚Äôs 1956 in Gilead, Iowa, towards the end of the Reverend Ames‚Äôs life, and he is absorbed in recording his family‚Äôs story, a legacy for the young son he will never see grow up. Haunted by his grandfather‚Äôs presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist. He is troubled, too, by his prodigal namesake, Jack (John Ames) Boughton, his best friend‚Äôs lost son who",
    "published_year": 2004,
    "average_rating": "4",
    "num_pages": 247,
    "ratings_count": 361,
},
{
  "title": "Warhost of Vastmark",
  "subtitle": "",
  "authors": "Janny Wurts",
  "categories": "Fiction",
  "thumbnail": "http://books.google.com/books/content?id=uOL0fpS9WZkC&printsec=frontcover&img=1&zoom=1&source=gbs_api",
  "description": "Tricked once more by his wily half-brother, Lysaer, Lord of Light, arrives at the tiny harbor town of Merior to find that Arithon's ship yards have been abandoned and meticulously destroyed, and that the Master of Shadow has disappeared as if into thin air. Meanwhile Arithon and the Mad Prophet Dakar are traveling on foot through the treacherous Kelhorn Mountains towards the Vastmark clans, there to raise further support for his cause. But raising a warhost is a costly business. Is it mere coincidence that Princess Talith‚ÄîLysaer's beautiful, headstrong wife‚Äîis taken captive and held for a vast ransom by a master brigand? The forces of light and shadow circle and feint, drawing ever closer to a huge conflict. And in the background the F",
  "published_year": 1995,
  "average_rating": "4",
  "num_pages": 522,
  "ratings_count": 2966,
},
{
  "title": "Witness for the Prosecution & Selected Plays",
  "subtitle": "",
  "authors": "Agatha Christie",
  "categories": "English drama",
  "thumbnail": "http://books.google.com/books/content?id=_9u7AAAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
  "description": "Newly-Jacketed Edition Designed To Celebrate The 50Th Anniversary Of Christie S Faultlessly Plotted Witness For The Prosecution And Other Outstanding Plays. The Perfect Complement To The Latest Edition Of The Mousetrap And Selected Plays (50Th Aniversary Edition). Headlining This Book Is Witness For The Prosecution Christie S Highly Successful Stage Play Which Won The New York Drama Critics Circle Award For Best Foreign Play. A Stunning Courtroom Drama, It Tells The Story Of A Scheming Wife Testifying Against Her Husband In A Shocking Murder Trial. The Wild Beauty Of A Seaside House Perched High On The Devonshire River Tern Provides A Stunning Back-Drop In Towards Zero As A Psychopathic Murderer Homes In On The Unsuspecting Victims. Passio",
  "published_year": 1995,
  "average_rating": "4",
  "num_pages": 352,
  "ratings_count": 3908,
},
{
  "title": "Spider's Web",
  "subtitle": "A Novel",
  "authors": "Charles Osborne;Agatha Christie",
  "categories": "Detective and mystery stories",
  "thumbnail": "http://books.google.com/books/content?id=gA5GPgAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
  "description": "A new 'Christie for Christmas' -- a full-length novel adapted from her acclaimed play by Charles Osborne Following BLACK COFFEE and THE UNEXPECTED GUEST comes the final Agatha Christie play novelisation, bringing her superb storytelling to a new legion of fans. Clarissa, the wife of a Foreign Office diplomat, is given to daydreaming. 'Supposing I were to come down one morning and find a dead body in the library, what should I do?' she muses. Clarissa has her chance to find out when she discovers a body in the drawing-room of her house in Kent. Desperate to dispose of the body before her husband comes home with an important foreign politician, Clarissa persuades her three house guests to become accessories and accomplices. It seems that the murdered man was not unknown to certain members of the house party (but which ones?), and the search begins for the murderer and the motive, while at the same time trying to persuade a police inspector that there has been no murder at all... SPIDER'S WEB was written in 1954 specifically for Margaret Lockwood and opened first at the Theatre Royal Nottingham before moving to the Savoy Theatre in London on 14 December 1954. With THE MOUSETRAP and WI",
  "published_year": 2000,
  "average_rating": "3.83",
  "num_pages": 241,
  "ratings_count": 5164,
},
{
  "title": "Rage of angels",
  "subtitle": " ",
  "authors": "Sidney Sheldon",
  "categories": "Fiction",
  "thumbnail": "http://books.google.com/books/content?id=FKo2TgANz74C&printsec=frontcover&img=1&zoom=1&source=gbs_api",
  "description": "A memorable, mesmerizing heroine Jennifer -- brilliant, beautiful, an attorney on the way up until the Mafia's schemes win her the hatred of an implacable enemy -- and a love more destructive than hate. A dangerous, dramatic world The Dark Arena of organized crime and flashbulb lit courtrooms where ambitious prosecutors begin their climb to political power.",
  "published_year": 1993,
  "average_rating": "3.93",
  "num_pages": 512,
  "ratings_count": 29532,
},
{
  "title": "The Problem of Pain",
  "subtitle": " ",
  "authors": "Clive Staples Lewis",
  "categories": "Christian life",
  "thumbnail": "http://books.google.com/books/content?id=Kk-uVe5QK-gC&printsec=frontcover&img=1&zoom=1&source=gbs_api",
  "description": "In The Problem of Pain, C.S. Lewis, one of the most renowned Christian authors and thinkers, examines a universally applicable question within the human condition: If God is good and all-powerful, why does he allow his creatures to suffer pain? With his signature wealth of compassion and insight, C.S. Lewis offers answers to these crucial questions and shares his hope and wisdom to help heal a world hungering for a true understanding of human nature.--Amazon.",
  "published_year": 2002,
  "average_rating": "4.09",
  "num_pages": 176,
  "ratings_count": 37569,
},
{
  "title": "Complications",
  "subtitle": "A Novel",
  "authors":"Danielle Steel",
  "categories": "Fiction",
  "thumbnail": "http://books.google.com/books/content?id=_2U9EAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
  "description": "NEW YORK TIMES BESTSELLER • Scandal and tragedy erupt against the backdrop of an exclusive Paris hotel in Danielle Steel’s riveting novel. Known for its luxurious accommodations and bespoke service, the Hotel Louis XVI has been the most lauded boutique hotel in all of Paris for decades, attracting an international clientele of the rich and famous. Now, after four years of renovations and the death of its legendary and beloved manager, it is set to reopen its doors at last. An esteemed group of loyal returning guests is set to descend upon the hotel, joined by a number of new faces who have managed to secure coveted bookings in the wake of last-minute cancellations. Awaiting them all is the Louis XVI’s new manager, Olivier Bateau, an anxious man whose lack of experience leaves him unprepared. He and his level-headed assistant manager, Yvonne Philippe, both strive to continue the hotel’s tradition of excellence. But they quickly realize that anything can happen at any moment, and on one cool September evening, everything does. A successful art consultant arrives at the hotel for the first time since her brutal divorce, and is surprised to find new love—if she is willing to risk her heart again. A new guest contemplates ending his life, and saves a life instead. A couple finds their once-in-a-lifetime trip interrupted by a tragic medical emergency, leaving the idyllic future they’ve long waited for hanging in the balance. And one of the hotel’s most high-profile guests, a French politician and assumed presidential candidate, holds a mysterious meeting in his suite that will threaten his life and legacy. Rocked by the events of this one fateful night, guests and staff alike brace themselves for the aftershock, as it quickly becomes apparent that more dramas and misfortunes are still in store. Danielle Steel tells an unforgettable story about a famed hotel, where a few complications quickly escalate into a matter of life and death, changing the lives of everyone who passes through its doors.",
  "published_year": 2001,
  "average_rating": "3.5",
  "num_pages": 257,
  "ratings_count": 9,
},
{
  "title": "Empires of the Monsoon",
  "subtitle": "A History of the Indian Ocean and Its Invaders",
  "authors": "Richard Hall",
  "categories": "Africa, East",
  "thumbnail": "http://books.google.com/books/content?id=MuPEQgAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
  "description": "Until Vasco da Gama discovered the sea-route to the East in 1497-9 almost nothing was known in the West of the exotic cultures and wealth of the Indian Ocean and its peoples. It is this civilization and its destruction at the hands of the West that Richard Hall recreates in this book. Hall's history of the exploration and exploitation by Chinese and Arab travellers, and by the Portuguese, Dutch and British alike is one of brutality, betrayal and colonial ambition.",
  "published_year": 1998,
  "average_rating": "4.41",
  "num_pages": 608,
  "ratings_count": 65,
},
{
  "title": "Master of the Game",
  "subtitle": " ",
  "authors": "Sidney Sheldon",
  "categories": "Adventure stories",
  "thumbnail": "http://books.google.com/books/content?id=TkTYp-Tp6_IC&printsec=frontcover&img=1&zoom=1&source=gbs_api",
  "description": "Kate Blackwell is an enigma and one of the most powerful women in the world. But at her ninetieth birthday celebrations there are ghosts of absent friends and absent enemies.",
  "published_year": 1982,
  "average_rating": "4.11",
  "num_pages": 489,
  "ratings_count": 43540,
},
{
  "title": "Neighbors",
  "subtitle": "A Novel",
  "authors": "Danielle Steel",
  "categories": "Fiction",
  "thumbnail": "http://books.google.com/books/content?id=E6kSEAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
  "description": "Pike Logan must pull two major world powers back from the brink of war in the latest pulse-pounding thriller from New York Times bestselling author and former Special Forces officer Brad Taylor",
  "published_year": 2021,
  "average_rating": "4",
  "num_pages": 290,
  "ratings_count": 7,
},
{
  "title": "Assassin's Apprentice",
  "subtitle": " ",
  "authors": "Robin Hobb",
  "categories": "American fiction",
  "thumbnail": "http://books.google.com/books/content?id=qTaGQgAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
  "description": "Kate Blackwell is an enigma and one of the most powerful women in the world. But at her ninetieth birthday celebrations there are ghosts of absent friends and absent enemies.",
  "published_year": 1996,
  "average_rating": "4.15",
  "num_pages": 460,
  "ratings_count": 133972,
}

];

const seedBooks = () => Books.bulkCreate(bookdata);

module.exports = seedBooks;
